spring:
  application:
    name: cloud-gateway
server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

zuul:
  routes:
    balance:
      path: /balance/**
      service-id: cpcs-balance
    boss:
      path:  /boss/**
      service-id: cpcr-boss
    
#ribbon:
##  eureka:
##    enabled: false
#  ReadTimeout: 60000  
#  ConnectTimeout: 60000
#
#cloud-client:
#  ribbon:
#    listOfServers: localhost:8050, localhost:8051
