server:
  port: 8014

logging:
  file: ./log/cpcr-micro-boss.log

feign:
  hystrix:
    enabled: true


spring:
  cloud:
    bus:
      trace:
        enable: true
  rabbitmq:
    host: 111.230.38.240
    port: 5672
    username: nova
    password: Nova2017

management:
  security:
    enabled: false

nova: adamjiangww
